// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DiskStats() {
  return window['go']['main']['App']['DiskStats']();
}

export function FanStats() {
  return window['go']['main']['App']['FanStats']();
}

export function GpuStats() {
  return window['go']['main']['App']['GpuStats']();
}

export function Info() {
  return window['go']['main']['App']['Info']();
}

export function NetStats() {
  return window['go']['main']['App']['NetStats']();
}

export function Sensors() {
  return window['go']['main']['App']['Sensors']();
}

export function Stats() {
  return window['go']['main']['App']['Stats']();
}
