// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function DiskStats():Promise<main.DiskStatsT>;

export function FanStats():Promise<Array<main.FanT>>;

export function GpuStats():Promise<Array<main.GpuT>>;

export function Info():Promise<main.InfoT>;

export function NetStats():Promise<Array<main.NetInterfaceT>>;

export function Sensors():Promise<Array<main.SensorT>>;

export function Stats():Promise<main.StatsT>;
