// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {net} from '../models';

export function Greet(arg1:string):Promise<string>;

export function Info():Promise<main.InfoT>;

export function NetStats():Promise<net.IOCountersStat>;

export function Stats():Promise<main.StatsT>;
